steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', '${_DOCKERFILE}', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
substitutions:
  _DOCKERFILE: deployment/Dockerfile.app
  _IMAGE: latch-browse-local
